all:
	make -C udd_perf
	make -C udd_perf_async
	make -C hash_perf
	make -C command_ut
	make -C iterate
	make -C iterate_async
	make -C sample_async
	make -C sample_sync

clean:
	make -C udd_perf clean
	make -C udd_perf_async clean
	make -C hash_perf clean
	make -C command_ut clean
	make -C iterate clean
	make -C iterate_async clean
	make -C sample_async clean
	make -C sample_sync clean

install:
	make -C udd_perf install
	make -C udd_perf_async install
	make -C hash_perf install
	make -C command_ut install
	make -C iterate install
	make -C iterate_async install
	make -C sample_async install
	make -C sample_sync install
